[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "build" 

[[redirects]]
  from = "/api/*"
  to = "http://gamecheb.tech/docs/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"} 